#!/bin/bash
turbostat_start() {
    rm -f /tmp/turbostat.fifo
    mkfifo /tmp/turbostat.fifo
    turbostat -J -o ${OUTPUT}/turbostat.out < /tmp/turbostat.fifo &
    echo $! | tee ${OUTPUT}/turbostat.pid
    # Starts turbostat
    echo > /tmp/turbostat.fifo
}

turbostat_stop() {
    # Force last value before kill.
    # Usefull when experiment was shorter than
    # turbostat's 5sec of collection interval
    echo > /tmp/turbostat.fifo
    kill -s SIGINT $(cat ${OUTPUT}/turbostat.pid)
    wait $(cat ${OUTPUT}/turbostat.pid) || true
    rm -f /tmp/turbostat.fifo
}

case ${MONITORING_SCHEDULED} in
    n) turbostat_start ;;
    y) (sleep ${MONITORING_START_DELAY}; turbostat_start; sleep ${MONITORING_STOP_DELAY}; turbostat_stop) & ;;
    *) exit 1 ;;
esac
