#!/bin/bash
turbostat_start() {
    turbostat -J -o ${OUTPUT}/turbostat.out &
    echo $! | tee ${OUTPUT}/turbostat.pid
}

turbostat_stop() {
    kill $(cat ${OUTPUT}/turbostat.pid)
    wait $(cat ${OUTPUT}/turbostat.pid) || true
}

case ${MONITORING_SCHEDULED} in
    n) turbostat_start ;;
    y) (sleep ${MONITORING_START_DELAY}; turbostat_start; sleep ${MONITORING_STOP_DELAY}; turbostat_stop) & ;;
    *) exit 1 ;;
esac
