#!/bin/bash
: ${TASKS}
tarball_dir=/tmp
# kernel=linux-5.4-rc1.tar.gz
kernel=linux-5.4.tar.xz
# kernel_url=https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/snapshot/$kernel
kernel_url=https://cdn.kernel.org/pub/linux/kernel/v5.x/$kernel

if ! [ -f ${tarball_dir}/${kernel} ]
then
    (cd ${tarball_dir} ; wget $kernel_url)
fi
rm -rf /tmp/kbuild
tar xf ${tarball_dir}/${kernel} -C /tmp/
mv /tmp/${kernel%%.tar.gz} /tmp/kbuild
make -C /tmp/kbuild defconfig
