#!/bin/bash

trace_sched_start() {
    echo 0 > /sys/kernel/debug/tracing/tracing_on
    echo nop > /sys/kernel/debug/tracing/current_tracer
    echo 0 > /sys/kernel/debug/tracing/events/enable
    echo $((2**20)) > /sys/kernel/debug/tracing/buffer_size_kb
    echo 1 > /sys/kernel/debug/tracing/events/sched/enable
    cat /sys/kernel/debug/tracing/set_event
    echo 1 > /sys/kernel/debug/tracing/tracing_on
}
trace_sched_stop() {
    echo 0 > /sys/kernel/debug/tracing/tracing_on
    echo 0 > /sys/kernel/debug/tracing/events/enable
    mkdir ${OUTPUT}/trace
    for cf in /sys/kernel/debug/tracing/per_cpu/cpu*
    do
	cpuname="${cf##*/}"
	touch "${OUTPUT}/trace/${cpuname}"
	dd iflag=nonblock if="${cf}/trace_pipe_raw" of="${OUTPUT}/trace/${cpuname}" || true
    done
    tar -C ${OUTPUT} -czf trace.tgz trace
    rm -rf ${OUTPUT}/trace
}
case ${MONITORING_SCHEDULED} in
        n) trace_sched_start ;;
        y) (sleep ${MONITORING_START_DELAY}; trace_sched_start; sleep ${MONITORING_STOP_DELAY}; trace_sched_stop) & ;;
        *) exit 1 ;;
esac
