#!/bin/bash
set -e -u
(
    BENCH=bench/oltpmysql;
    OUTPUT+="/${BENCH}"
    ./scripts/time ${BENCH}/run > ${OUTPUT}/time.out 2> ${OUTPUT}/time.err
) &
sleep 60
(
    BENCH=bench/kbuild;
    OUTPUT+="/${BENCH}"
    ./scripts/time ${BENCH}/run > ${OUTPUT}/time.out 2> ${OUTPUT}/time.err
) &
wait
