#!/bin/bash
set -e -u
(
    OUTPUT+="/oltp-mysql"
    ./scripts/time bench/oltp-mysql/run > ${OUTPUT}/time.out 2> ${OUTPUT}/time.err
) &
sleep 60
(
    OUTPUT+="/kbuild"
    ./scripts/time bench/kbuild/run > ${OUTPUT}/time.out 2> ${OUTPUT}/time.err
) &
wait
