#!/bin/bash

trace_cmd_start() {
    trace-cmd record -o ${OUTPUT}/trace.dat ${TRACECMD_RECORD_OPT} -- bash -c "echo \$\$ | tee ${OUTPUT}/trace-cmd.sleep.pid; exec sleep inf" &
    echo $! | tee ${OUTPUT}/trace-cmd.pid
    until [ -f ${OUTPUT}/trace-cmd.sleep.pid ]
    do
	echo 'Waiting for trace-cmd'
	sleep 1
    done
}
trace_cmd_stop() {
    # do not kill trace-cmd.pid
    kill $(cat ${OUTPUT}/trace-cmd.sleep.pid)
    wait $(cat ${OUTPUT}/trace-cmd.pid) || true
    tar czf "${OUTPUT}/trace.dat.tgz" ${OUTPUT}/trace.dat
    rm -f ${OUTPUT}/trace.dat
}
case ${MONITORING_SCHEDULED} in
        n) trace_cmd_start ;;
        y) (sleep ${MONITORING_START_DELAY}; trace_cmd_start; sleep ${MONITORING_STOP_DELAY}; trace_cmd_stop) & ;;
        *) exit 1 ;;
esac
