#!/bin/bash
: ${TASK}

if ! [ -d /tmp/mysql-server ]
then
	git clone --branch 8.0 --depth 1 https://github.com/mysql/mysql-server /tmp/mysql-server
fi
rm -rf /tmp/mysql-server/build
mkdir /tmp/mysql-server/build
(cd /tmp/mysql-server/build; cmake .. -DDOWNLOAD_BOOST=1 -DWITH_BOOST=boost)
