#!/bin/bash
set -e -u
export FORCE_TIMES_TO_RUN=1
export TEST_RESULTS_NAME=schedrecord
export TEST_RESULTS_IDENTIFIER=schedrecord
export TEST_RESULTS_DESCRIPTION=schedrecord
echo  "${PHORONIX_TEST_ARGUMENTS}" | tr '-' '\n' | phoronix-test-suite run ${PHORONIX} >${OUTPUT}/run.out 2>${OUTPUT}/run.err
