#!/bin/bash

set -e -x -u

infloop() { set +x; while :; do :; done; }
getpid() {
    read f < /proc/self/stat
    pid=${f%% *}
}
cpupin() {
    getpid
    echo pid=$pid
    cpumask="$1"
    fnt="$2"
    cgroup="/sys/fs/cgroup/cpuset/freq-active-core/$pid"
    ! test -e "$cgroup"
    mkdir -p "$cgroup"
    # Setting defaults
    cp /sys/fs/cgroup/cpuset/cpuset.cpus /sys/fs/cgroup/cpuset/freq-active-core/cpuset.cpus
    cp /sys/fs/cgroup/cpuset/freq-active-core/cpuset.cpus "$cgroup/cpuset.cpus"
    cp /sys/fs/cgroup/cpuset/cpuset.mems /sys/fs/cgroup/cpuset/freq-active-core/cpuset.mems
    cp /sys/fs/cgroup/cpuset/freq-active-core/cpuset.mems "$cgroup/cpuset.mems"
    #
    tee "$cgroup/cpuset.cpus" <<< "$cpumask"
    (
	getpid
	echo pid=$pid
	tee "$cgroup/tasks" <<< $pid
	$fnt
    ) &
    clean() {
	set -x
	kill -9 $(cat "$cgroup/tasks")
	until rmdir $cgroup; do sleep 1; done
    }
    done='sleep 1'
    trap 'clean; done=break' SIGTERM
    set +x
    while :; do $done; done
}
scaling_cur_freq() {
    for cpu in /sys/devices/system/cpu/cpu{0..9}*
    do
	(
	    done='sleep 1'
	    trap 'done=break' SIGTERM
	    cpuid=${cpu##*cpu}
	    set +x
	    exec 1>"${cpuid}.csv"
	    # echo "cpu,freq"
	    while :
	    do
		echo "${cpuid},$(cat $cpu/cpufreq/scaling_cur_freq)"
		$done
	    done
	) &
	echo $!
    done
}
tokill=$(scaling_cur_freq)
sleep 1
cpupin 10-10 infloop &
cpupinpid=$!
sleep 5
kill $cpupinpid
wait $cpupinpid
sleep 1
kill $tokill
wait $tokill
