#!/usr/bin/env python3

import sys
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt

# Usage
#   ./barplot.py input.csv output.pdf output-no-ticks.pdf

# Input file can be generated by heatmap.py by adding the following line after all the data treatments:
#      df.to_csv(output_file+".csv", float_format="%2.1f")

_, input_file, output_file, output_file_noticks = sys.argv

data = pd.read_csv(input_file, delimiter=',')
newData = pd.DataFrame(columns=["bench", "sched", "gain"])

for d in data.iterrows(): 
    newData = newData.append({ 'bench': d[1]['Unnamed: 0'],
                               'sched': 'lp-2',
                               'gain':   d[1]['lp-2'] },
                             ignore_index=True) 
    newData = newData.append({ 'bench': d[1]['Unnamed: 0'],
                               'sched': 'dp',
                               'gain':   d[1]['dp'] },
                             ignore_index=True) 

fig = plt.figure(figsize=(17,2.5))
plt.xticks(rotation=90)
sb.barplot(data=newData, x='bench', y='gain', hue='sched')
plt.xlabel("")
plt.ylabel('Gain vs Linux 5.4 (%)')
plt.grid(axis='x')
fig.savefig(output_file, bbox_inches='tight')
plt.tick_params(
    axis='x',          # changes apply to the x-axis
    which='both',      # both major and minor ticks are affected
    bottom=False,      # ticks along the bottom edge are off
    top=False,         # ticks along the top edge are off
    labelbottom=False) # labels along the bottom edge are off
fig.savefig(output_file_noticks, bbox_inches='tight')
