#!/bin/bash
set -e -u
prog="${1}"
shift

# Cleanup
if [[ -d ./rootproc ]]
then
	if mount | grep -q $(realpath ./rootproc )
	then
		umount ./rootproc
	fi
	rmdir ./rootproc
fi

# Prepare
mkdir ./rootproc
mount --bind /proc ./rootproc

if [ ${DO_NOT_UNSHARE:-n} == y ]
then
    exec "${prog}" "${@}"
else
    exec unshare -mpf --mount-proc -- "${prog}" "${@}"
fi
